format: 0.3.0
project:
  name: "Migrate_0-1-0_to_0-3-0"
  type: wasm/assemblyscript
source:
  schema: ../schema.graphql
  module: ../index.ts
  import_redirects:
  - uri: "ens/ipfs.polywrap.eth"
    schema: ../../../../../../../../interfaces/ipfs/build/schema.graphql
extensions:
  build: ./polywrap.build.yaml
  meta: ./polywrap.meta.yaml
  deploy: ./polywrap.deploy.yaml