format: 0.4.0
jobs:
  fs_to_ipfs:
    config:
      provider: http://localhost:8545
      gatewayUri: $IPFS_GATEWAY_URI
    steps:
      - name: ipfs_deploy
        package: ipfs
        uri: wrap://fs/../wrapper
