[tool.bandit]
# nothing

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ["py310"]

[tool.mypy]
python_version = "3.10"
allow_redefinition = true
disallow_any_decorated = true
disallow_any_explicit = true
disallow_any_expr = true
disallow_any_generics = true
disallow_any_unimported = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
no_implicit_optional = true
strict = true
strict_equality = true
strict_optional = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.pydocstringformatter]
max-line-length = 120
write = true