format: 0.2.0
project:
  name: "Migration_sample"
  type: wasm/assemblyscript
source:
  schema: ../schema.graphql
  module: ../index.ts
  import_abis:
    - uri: "wrap://ens/uri-resolver.core.polywrap.eth"
      abi: ../../../../../../../../interfaces/uri-resolver/build/schema.graphql
extensions:
  build: ./polywrap.build.yaml
  meta: ./polywrap.meta.yaml
  deploy: ./polywrap.deploy.yaml
