format: "0.2.0"
sequences:
  - name: test
    config:
      provider: 'http://localhost:8545'
      gatewayUri: $IPFS_GATEWAY_URI
      ensRegistryAddress: $ENS_REG_ADDR
      ensRegistrarAddress: $ENS_REGISTRAR_ADDR
      ensResolverAddress: $ENS_RESOLVER_ADDR
    steps:
      - name: ipfs_deploy
        package: ipfs
        uri: fs/./build
      - name: from_deploy
        package: ens
        uri: $$ipfs_deploy
        config:
          domainName: foo
          ports:
            ethereum: 8545
      - name: ens_register
        package: ens-recursive-name-register
        uri: wrap://ens/test2.eth
      - name: from_deploy2
        package: ens
        uri: $$ipfs_deploy
        config:
          domainName: test2.eth
          ports:
            ethereum: 8545