format: "0.2"
sequences:
  - name: test
    config:
      gatewayUri: $IPFS_GATEWAY_URI
    steps:
      - name: ipfs_deploy
        package: ipfs
        uri: fs/./build
      - name: from_deploy
        package: local-dev-ens
        uri: $$ipfs_deploy
        config:
          domainName: foo
          ports:
            ethereum: 8545
      - name: from_deploy2
        package: local-dev-ens
        uri: $$ipfs_deploy
        config:
          domainName: test2.eth
          ports:
            ethereum: 8545