format: 0.4.0
jobs:
  test:
    config:
      gatewayUri: $IPFS_GATEWAY_URI
    steps:
      - name: ipfs_deploy
        package: ipfs
        uri: fs/../wrapper
        config:
          gatewayUri: $NON_LOADED_VAR
