format: 0.4.0
jobs:
  test:
    config:
      gatewayUri: $IPFS_GATEWAY_URI
    steps:
      - name: ipfs_deploy_1
        package: ipfs
        uri: fs/../wrapper
      - name: ipfs_deploy_2
        package: ipfs
        uri: fs/../wrapper
        config:
          gatewayUri: "this_should_throw"
      - name: ipfs_deploy_3
        package: ipfs
        uri: fs/../wrapper
